filetype plugin indent on
set encoding=utf8 " Use utf-8 as default encoding

" Vundler
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" My plugins to install/update with vundler See http://vimawesome.com/
Plugin 'gmarik/snipmate.vim'
Plugin 'gmarik/vundle'
Plugin 'scrooloose/nerdcommenter'
Plugin 'tpope/vim-rails'
Plugin 'kshenoy/vim-signature'

let mapleader = ","

let NERDSpaceDelims = 2

set number

set wrap " Line wrapping on
set ts=2 sts=2 sw=2 expandtab " Use spaces instead tabs. From: http://vimcasts.org/episodes/tabs-and-spaces/

" Disable defaults
set noswapfile " Dont create *.swp* files. Useful to use with dropbox.
set nobackup " Dont create ~ files.
set nocursorline " Dont underline all line.
setlocal incsearch " Set search *dinamic*
set hlsearch " No highlight searchs

" Show invisibles
" http://vimcasts.org/episodes/show-invisibles/
set list
set listchars=tab:\|\ ,trail:·,eol:¬

" Status line
" Customize status line
" `:help statusline`
set laststatus=2 " Always show statusline
set statusline=%<%f\ \[%{&ff}\]\ %y\ %h%m%r%=%-14.(%c%V%)\ %l/%L[%P]

" Disable arrow keys
" http://vimcasts.org/blog/2013/02/habit-breaking-habit-making/
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

map <leader>/ :set hlsearch!<cr> " Toggle hlsearch :)

" pay attention when the line has more then 80 characters. Tip by
" @MarceloCajueiro
match Error /\%80v.\+/

"set textwidth=80 " Use gq when in visual mode

colorscheme desert
syntax on

" From: http://ryanselk.com/2015/05/19/terminals-in-neovim/
tnoremap <C-q> <C-\><C-n>
