# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

[[ -e ~/.zprofile ]] && source ~/.zprofile
[[ -e ~/.xprofile ]] && source ~/.xprofile

xhost local:root

xautolock -time 1 -locker /usr/bin/i3lock-fancy -detectsleep >/dev/null 2>/dev/null &

exec /usr/bin/dbus-launch /usr/bin/i3
