unsetopt correct
#
# Load machine only configuration
#
if [[ -f "$HOME/local/etc/profile" ]]; then
  source "$HOME/local/etc/profile"
fi

#
# chruby
#
if [[ -d "/usr/local/share/chruby" ]]; then
  source "/usr/local/share/chruby/chruby.sh"
  source "/usr/local/share/chruby/auto.sh"
  chruby 2
fi

#
# Aliases
#
alias quit='exit'
alias q='exit'
alias :q='exit'
alias :q!='exit'
alias :e='vim'

alias -g CF=' | cut -d: -f1 | sort | uniq'
alias -g L=' | less'

alias mux='tmuxinator'

alias rm='echo "This is not the command you are looking for."; false'

alias rspec='bundle exec rspec --no-color --fail-fast --seed 1'
alias rake='bundle exec rake'

#
# From http://grml.org/zsh/zsh-lovers.html
#
setopt autocd
setopt no_hup
setopt hist_verify
setopt share_history
setopt no_clobber

#
# https://wiki.archlinux.org/index.php/Zsh
#
bindkey -v
autoload -U compinit
compinit
PROMPT='%?  '
RPROMPT=''

#
# https://wiki.gentoo.org/wiki/Zsh/Guide
#
export HISTSIZE=2000
export HISTFILE="$HOME/.history"
export SAVEHIST=$HISTSIZE
setopt hist_ignore_all_dups
setopt hist_ignore_space

#
# https://github.com/zsh-users/zsh-history-substring-search
#
source ~/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.zsh-history-substring-search/zsh-history-substring-search.zsh
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down
ZSH_HIGHLIGHT_HIGHLIGHTERS=()
